Don't use custom error output code
Python's default output for exceptions contains *more* information than `print(e)` since it contains the traceback, which shows you which line failed, as well as the representation of the exception. Contrast:

```
$ # current implementation
$ python -c "try:
>     1/0
> except Exception as e:
>     print(e)"
division by zero
$ python -c "try:\n    1/0\nexcept Exception as e:\n    print(e)"                                                                                                                             ⏎
  File "<string>", line 1
    try:\n    1/0\nexcept Exception as e:\n    print(e)
                                                      ^
SyntaxError: unexpected character after line continuation character

```